requires:
  - name: macaroni-phoenix-base
    category: "seed"
    version: ">=0"
env:
- JOBS=10
- GIT_HISTORY_ENTRIES=3000
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
prelude:
- >-
  mv kits-versions / &&
  ego sync &&
  cd /var/git/meta-repo/kits &&
  chown root:root -R /var/git/meta-repo/kits &&
  ls -l &&
  for i in $(ls .) ; do
  echo $i ;
  if [ -e /kits-versions/$i.yml ] ; then
  hash=$(yq r /kits-versions/$i.yml 'commit') ;
  echo "For kit $i set hash $hash" ;
  pushd $i ;
  git pull -ff --depth=$GIT_HISTORY_ENTRIES ;
  git checkout $hash || exit 1 ;
  popd ;
  fi ;
  done &&
  chown portage:portage -R /var/git/meta-repo/kits
# We need setup correctly ego arch,subarch,build.
# This is not needed on macaroni-funtoo because we starts from
# a funtoo stage3.
- >-
  ego profile arch {{ ( index .Values.labels "ego.arch" ) }} &&
  ego profile build {{ ( index .Values.labels "ego.build" ) }} &&
  ego profile subarch {{ ( index .Values.labels "ego.subarch" ) }} &&
  ego profile flavor {{ ( index .Values.labels "ego.flavor" ) }} &&
  ego profile

