project_name: Macaroni Security
build:
  skip: true
release:
  header: |
    ## Macaroni Security Repository {{ .Tag }}!

    A new tag of Phoenix Security Repository is out!

    See the above list for all upgrade details.

    Many thanks to all [Funtoo](https://www.funtoo.org/) devs that are the sap of all this.

    Enjoy!

    Any user that wants to support our work for Macaroni could do this through the Github [Sponsor](https://github.com/sponsors/geaaru) or alternative to add a :star: to our projects.

changelog:
  sort: asc
  groups:
    - title: New packages
      regexp: ".*new.*"
      order: 1
    - title: Packages
      regexp: ".*Bump.*"
      order: 2
    - title: Reverts
      regexp: '^Revert.*'
      order: 3
    - title: Others
      order: 9999
  filters:
    exclude:
      - '^.github'
      - '^github'
      - '^portage-converter'
      - '^.gorelease'
