requires:
  - name: "kernel"
    category: "seed-5.15"
    version: ">=0"
env:
- FEATURES="-sandbox -usersandbox -ipc-sandbox -pid-sandbox -network-sandbox"
package_dir: /{{ .Values.name }}
steps:
- >-
  epro list &&
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }} -pv -t
  {{- end }}
- |
  {{- if .Values.use_flags }}
  USE="{{ join " " .Values.use_flags }}" emerge {{ ( index .Values.labels "emerge.packages" ) }}
  {{- else }}
  emerge -j ${JOBS} {{ ( index .Values.labels "emerge.packages" ) }}
  {{- end }}
- |
  eval 'rm -rf /{{ .Values.name }} || true' && mkdir /{{ .Values.name }} && \
  luet-portage --dir /{{ .Values.name }} {{ ( index .Values.labels "emerge.packages" ) }}
# It seems that the compression is not handled correct from the ebuild
# I run manually compression for every module
- >-
  for i in /{{ .Values.name }}/lib/modules/{{ ( index .Values.labels "kernel.version" ) }}-macaroni/misc/*.ko ; do
  zstd ${i} -o ${i}.zst --rm ;
  done
excludes:
# Funtoo/Portage stuff
- ^/var/db/pkg/
- ^/var/cache/portage/
- ^/var/git/

# Exclude files available from kernel/virtualbox-common
- ^/etc/modprobe.d/
- ^/usr/lib/modules-load.d/
