prelude:
# dev-util/kbuild is needed for virtualbox-guest-additions
- >-
  export LUET_YES=true &&
  export LUET_NOLOCK=true &&
  anise repo update && anise i repository/macaroni-security-dev &&
  anise repo update && anise upgrade &&
  anise i dev-util/cbindgen dev-libs/libnatspec app-arch/zip &&
  anise cleanup
requires:
- category: "seed"
  name: "macaroni-phoenix-base"
  version: ">=0"
